name: Trigger auto deployment for quizmanagerapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/quizmanagerapi-AutoDeployTrigger-a083b2e2-b207-41c4-b681-c4eb9e3245ba.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.QUIZMANAGERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QUIZMANAGERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QUIZMANAGERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.QUIZMANAGERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QUIZMANAGERAPI_REGISTRY_PASSWORD }}
          containerAppName: quizmanagerapi
          resourceGroup: QuizManager
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


